### ISSUE TITLE
licensing

### ISSUE THREAD

**Issue by loriab** [psi4/dkh#1]
The DKH website doesn't have a link to their code, just to software packages that implement it (their list doesn't include Psi4). So,
- [ ] inform Reiher of this hosting and CMake build scheme and make sure he's ok with it. He was ok with exactly this code in Psi4 itself, so no real reason a separate repo should be a problem.
- [ ] inform Reiher of imminent conda package. @loriab has talking points, if required
- [ ] see if there's a license we can put into this repo

**Comment by CDSherrill** [comment]
If it was Jet who initially got this going, maybe he should communicate
with Reiher

**Comment by loriab** [comment]
@jturney

**Comment by loriab** [comment]
Correspondence with Prof. Reiher indicates he approves of this repository with an LGPL license.
